version: "3"
services:
  frontend:
    build: ./mortar-app-frontend
    image: mortar-frontend:latest
    container_name: mortar_frontend
    ports:
      - "80:80"
  
  backend:
    build: ./backend
    image: mortar-backend:latest
    container_name: mortar_backend
    ports:
      - "8000:8000"

